ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "autoSync" BOOLEAN DEFAULT false;
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "syncFrequency" TEXT DEFAULT 'daily';
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "lastSyncedAt" TIMESTAMP(3);
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "sourceUrl" TEXT;
